# Generated by Django 3.2.12 on 2022-02-10 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeRequest',
            fields=[
                ('trans_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('cc_num', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('errors', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeResponse',
            fields=[
                ('stripe_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=24)),
                ('amount', models.IntegerField()),
                ('action', models.CharField(max_length=24)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middleware_api'
                                                                                                 '.striperequest')),
            ],
        ),
    ]
