# Generated by Django 3.2.12 on 2022-02-10 19:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_num', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('trans_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cc_num', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('trans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middleware_api.request')),
            ],
        ),
    ]
